# Generated by Django 4.0.4 on 2022-05-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
